# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run:
          name: Install JFrog CLI
          command: 
            curl -fL https://getcli.jfrog.io | sh
            chmod a+x jfrog && sudo mv jfrog /usr/local/bin
      - run:
          name: Configure JFrog CLI
          command: 
            jfrog rt config server1 --url=https://swarnenduk.jfrog.io/artifactory --user=admin --password=Password6
            jfrog rt c show
      - run:
          name: Running the build
          command: 
            jfrog rt gradlec --server-id-resolve=server1 --server-id-deploy=server1 --repo-resolve=gradle-dev --repo-deploy=gradle-dev-local --use-wrapper=true --uses-plugin=true
            frog rt gradle clean artifactoryPublish --build-name=gradle-circleci --build-number=${CIRCLE_BUILD_NUM}
            jfrog rt sp "gradle-release/GitLab-Gradle-Minimal/1.0-SNAPSHOT/GitLab-Gradle-Minimal-1.0-SNAPSHOT.jar" "artifacts=artifactory"
            jfrog rt bce --build-name=gradle-circleci --build-number=${CIRCLE_BUILD_NUM}
            jfrog rt bp gradle-circleci ${CIRCLE_BUILD_NUM}
